use datawarehouse;

CREATE TABLE [Dim_Customer] (
	[CUSTOMER_KEY] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[CUSTOMER_ID] int,
    [FIRST_NAME] VARCHAR(255),
    [LAST_NAME] VARCHAR(255),
    [CITY] NVARCHAR(255),
    [STATE] NVARCHAR(255),
    [ZIPCODE] BIGINT,
    [TYPE] VARCHAR(50),
    [BIRTH_DATE] DATE
)

CREATE TABLE [Dim_Employee] (
	[EMPLOYEE_KEY] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[EMPLOYEE_ID] INT,
    [FIRST_NAME] VARCHAR(255),
    [LAST_NAME] VARCHAR(255),
    [CATEGORY] NVARCHAR(255),
    [EMPLOYMENT_DATE] DATE,
    [BIRTH_DATE] DATE,
    [EDUCATION_LEVEL] NVARCHAR(255),
    [GENDER] VARCHAR(50),
	[ANTIQUITY] INT,
    [AGE] INT
)

CREATE TABLE [Dim_Product] (
    [PRODUCT_KEY] INT PRIMARY KEY,
    [DETAIL] VARCHAR(50),
    [CONTAINER_CAPACITY] DECIMAL(3,2),
    [UNIT] NVARCHAR(88)
)

CREATE TABLE [Dim_Date] (
    [DATE_KEY] INT PRIMARY KEY,
    [SEMESTER] NVARCHAR(16),
    [BIMESTER] NVARCHAR(10),
    [DATE] DATE,
    [YEAR] INT,
    [MONTH] INT,
    [DAY] INT
)

CREATE TABLE [Dim_GrupoEtario] (
    [GRUPOETARIO_KEY] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [DETAIL] VARCHAR(255),
    [DESDE_AGE] INT,
    [HASTA_AGE] INT
)


CREATE TABLE [Fact_Billing] (
    [BILLING_KEY] INT,
    [PRODUCT_KEY] INT,
    [DATE_KEY] INT,
    [CUSTOMER_KEY] INT,
    [EMPLOYEE_KEY] INT,
    [GRUPOETARIO_KEY] INT,
    [REGION] NVARCHAR(45),
    [QUANTITY] INT,
    [PRICE] FLOAT,
    [QUANTITY_LITER] DECIMAL(14,2),
    [TOTAL_PRICE] FLOAT,
    [TOTAL_PRICE_WITH_DISCOUNT] FLOAT,
    [DISCOUNT] SMALLINT,
    PRIMARY KEY ([BILLING_KEY], [PRODUCT_KEY]),
    FOREIGN KEY ([DATE_KEY]) REFERENCES Dim_Date([DATE_KEY]),
    FOREIGN KEY ([CUSTOMER_KEY]) REFERENCES Dim_Customer([CUSTOMER_KEY]),
    FOREIGN KEY ([EMPLOYEE_KEY]) REFERENCES Dim_Employee([EMPLOYEE_KEY]),
    FOREIGN KEY ([PRODUCT_KEY]) REFERENCES Dim_Product([PRODUCT_KEY]),
    FOREIGN KEY ([GRUPOETARIO_KEY]) REFERENCES Dim_GrupoEtario([GRUPOETARIO_KEY])
);