use datawarehouse;

CREATE TABLE [Dim_Customer] (
	[CUSTOMER_KEY] INT,
	[CUSTOMER_ID] int,
    [FIRST_NAME] VARCHAR(255),
    [LAST_NAME] VARCHAR(255),
    [CITY] NVARCHAR(255),
    [STATE] NVARCHAR(255),
    [ZIPCODE] BIGINT,
    [TYPE] VARCHAR(50),
    [BIRTH_DATE] DATE,
	[AGE] INT
)

CREATE TABLE [Dim_Employee] (
	[EMPLOYEE_KEY] INT,
	[EMPLOYEE_ID] INT,
    [FIRST_NAME] VARCHAR(255),
    [LAST_NAME] VARCHAR(255),
    [CATEGORY] NVARCHAR(255),
    [EMPLOYMENT_DATE] DATE,
    [BIRTH_DATE] DATE,
	[AGE] INT,
    [EDUCATION_LEVEL] NVARCHAR(255),
    [GENDER] VARCHAR(50)
)

CREATE TABLE [Dim_Product] (
    [PRODUCT_KEY] INT,
    [DETAIL] VARCHAR(50),
    [CONTAINER_CAPACITY] DECIMAL(3,2),
    [UNIT] NVARCHAR(88)
)

CREATE TABLE [Dim_Date] (
    [DATE_KEY] INT,
    [SEMESTER] NVARCHAR(16),
    [BIMESTER] NVARCHAR(10),
    [DATE] DATE,
    [YEAR] INT,
    [MONTH] INT,
    [DAY] INT
)